name: Deployment build

on:
  deployment:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install lftp
      run: apt install lftp
    - name: Install Dependencies
      run: npm install
    - name: Build the app
      run: |
        npm run build
        echo hoi
        
