name: Deployment build

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install lftp
      run: sudo apt install lftp neofetch; neofetch -L
    - name: Install Dependencies
      run: npm install
    - name: Build the app
      run: npm run build
    - name: Deploy app to rohanphoto
      env: 
        host: ${{ secrets.ftp_host }}
        user: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}
      run: lftp -e "open $host; user $user $password; mirror -X .* -X .*/ --reverse --verbose --delete dist/ ./public_html/rohanphoto; bye"
