name: Deployment build

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install lftp
      run: sudo apt install lftp
    - name: Install Dependencies
      run: npm install
    - name: Build the app
      run: npm run build
    - name: Deploy app to rohanphoto
      run: lftp -c "set ftp:ssl-allow no; open -u $ftp_user,$ftp_password $ftp_host; mirror -Rev dist/ ./public_html/rohanphoto  --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/"
        
