name: Deployment build

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install lftp
      run: sudo apt install lftp
    - name: Install Dependencies
      run: npm install
    - name: Build the app
      run: npm run build
    - name: Deploy app to web server
      env:
        host: ${{ secrets.ftp_host }}
        user: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}
      run: lftp -c "set ftp:ssl-allow no; open -u $user,$password $host; mirror --reverse --verbose --delete dist/ ./domains/580626.infhaarlem.nl/public_html/rohanphoto --exclude-glob .git* --exclude .git/; bye"
